In [1]:
import pandas as pd
from pathlib import Path
import sys
sys.path.append("..")
from src.data import recoger_data

In [2]:
DATA_PATH = Path("../data")
RAW_PATH = DATA_PATH / "raw"
PROCESSED_PATH = DATA_PATH / "processed"


url = "https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/estacion-bicicleta.json?rows=300"

datos = recoger_data(url)

In [3]:
df = pd.json_normalize(datos["result"])
pd.set_option('display.max_colwidth', None)
df.to_csv(RAW_PATH / "datos_crudos.csv")

In [4]:
df.head(5)

,id,about,title,estado,estadoEstacion,address,tipoEquipamiento,bicisDisponibles,anclajesDisponibles,lastUpdated,description,descripcion,icon,geometry.type,geometry.coordinates
0,279,http://www.zaragoza.es/ciudad/viapublica/movilidad/bici/detalle_Bizi?oid=279,193- Pza. La Ermita,IN_SERVICE,http://vocab.linkeddata.es/datosabiertos/kos/transporte/bicicleta-publica/tipo-estado-estacion/no-operativa,193- Pza. La Ermita,http://vocab.linkeddata.es/datosabiertos/kos/urbanismo-infraestructuras/equipamiento/tipo-equipamiento/estacion-de-bicicletas,3,16,2026-07-22T11:53:09,<ul><li>Estado: Operativa</li><li>Bicis disponibles: 3</li><li>Anclajes disponibles: 16</li></ul><p>Actualizado: 11:53</p>,Datos de la estación bizi 193- Pza. La Ermita,//www.zaragoza.es/contenidos/iconos/bizi/conbicis.png,Point,"[-0.911215893796391, 41.63149540266168]"
1,278,http://www.zaragoza.es/ciudad/viapublica/movilidad/bici/detalle_Bizi?oid=278,270- Delicias Autobuses,IN_SERVICE,http://vocab.linkeddata.es/datosabiertos/kos/transporte/bicicleta-publica/tipo-estado-estacion/no-operativa,270- Delicias Autobuses,http://vocab.linkeddata.es/datosabiertos/kos/urbanismo-infraestructuras/equipamiento/tipo-equipamiento/estacion-de-bicicletas,18,1,2026-07-22T11:53:09,<ul><li>Estado: Operativa</li><li>Bicis disponibles: 18</li><li>Anclajes disponibles: 1</li></ul><p>Actualizado: 11:53</p>,Datos de la estación bizi 270- Delicias Autobuses,//www.zaragoza.es/contenidos/iconos/bizi/conbicis.png,Point,"[-0.9107841716732368, 41.65951733457972]"
2,277,http://www.zaragoza.es/ciudad/viapublica/movilidad/bici/detalle_Bizi?oid=277,150- Mrio. Siresa: Dr. Iranzo,IN_SERVICE,http://vocab.linkeddata.es/datosabiertos/kos/transporte/bicicleta-publica/tipo-estado-estacion/no-operativa,150- Mrio. Siresa: Dr. Iranzo,http://vocab.linkeddata.es/datosabiertos/kos/urbanismo-infraestructuras/equipamiento/tipo-equipamiento/estacion-de-bicicletas,2,16,2026-07-22T11:53:09,<ul><li>Estado: Operativa</li><li>Bicis disponibles: 2</li><li>Anclajes disponibles: 16</li></ul><p>Actualizado: 11:53</p>,Datos de la estación bizi 150- Mrio. Siresa: Dr. Iranzo,//www.zaragoza.es/contenidos/iconos/bizi/conbicis.png,Point,"[-0.8640994330671391, 41.64758556666017]"
3,276,http://www.zaragoza.es/ciudad/viapublica/movilidad/bici/detalle_Bizi?oid=276,127- Navarra: Rioja,IN_SERVICE,http://vocab.linkeddata.es/datosabiertos/kos/transporte/bicicleta-publica/tipo-estado-estacion/no-operativa,127- Navarra: Rioja,http://vocab.linkeddata.es/datosabiertos/kos/urbanismo-infraestructuras/equipamiento/tipo-equipamiento/estacion-de-bicicletas,1,18,2026-07-22T11:53:09,<ul><li>Estado: Operativa</li><li>Bicis disponibles: 1</li><li>Anclajes disponibles: 18</li></ul><p>Actualizado: 11:53</p>,Datos de la estación bizi 127- Navarra: Rioja,//www.zaragoza.es/contenidos/iconos/bizi/conbicis.png,Point,"[-0.908685551690069, 41.655535911165344]"
4,275,http://www.zaragoza.es/ciudad/viapublica/movilidad/bici/detalle_Bizi?oid=275,20- Camón Aznar: C. Augusto,IN_SERVICE,http://vocab.linkeddata.es/datosabiertos/kos/transporte/bicicleta-publica/tipo-estado-estacion/no-operativa,20- Camón Aznar: C. Augusto,http://vocab.linkeddata.es/datosabiertos/kos/urbanismo-infraestructuras/equipamiento/tipo-equipamiento/estacion-de-bicicletas,19,0,2026-07-22T11:53:09,<ul><li>Estado: Operativa</li><li>Bicis disponibles: 19</li><li>Anclajes disponibles: 0</li></ul><p>Actualizado: 11:53</p>,Datos de la estación bizi 20- Camón Aznar: C. Augusto,//www.zaragoza.es/contenidos/iconos/bizi/conbicis.png,Point,"[-0.8853921642559097, 41.65246416373115]"

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    276 non-null    str
 1   about                 276 non-null    str
 2   title                 276 non-null    str
 3   estado                276 non-null    str
 4   estadoEstacion        276 non-null    str
 5   address               276 non-null    str
 6   tipoEquipamiento      276 non-null    str
 7   bicisDisponibles      276 non-null    int64
 8   anclajesDisponibles   276 non-null    int64
 9   lastUpdated           276 non-null    str
 10  description           276 non-null    str
 11  descripcion           276 non-null    str
 12  icon                  276 non-null    str
 13  geometry.type         276 non-null    str
 14  geometry.coordinates  276 non-null    object
dtypes: int64(2), object(1), str(12)
memory usage: 32.5+ KB

In [6]:
df.describe()

       bicisDisponibles  anclajesDisponibles
count        276.000000           276.000000
mean           6.007246            13.380435
std            6.435127             5.765431
min            0.000000             0.000000
25%            1.000000             9.000000
50%            3.000000            15.000000
75%           10.000000            18.000000
max           27.000000            30.000000

In [7]:
df.columns

Index(['id', 'about', 'title', 'estado', 'estadoEstacion', 'address',
       'tipoEquipamiento', 'bicisDisponibles', 'anclajesDisponibles',
       'lastUpdated', 'description', 'descripcion', 'icon', 'geometry.type',
       'geometry.coordinates'],
      dtype='str')

# Normalización de dataframe

Elimino columnas que no sirven para el analisis.

In [8]:
columnas_eliminar = ["about","estadoEstacion","tipoEquipamiento","icon","title","description","descripcion","geometry.type"]

df = df.drop(columns=columnas_eliminar)

In [9]:
df.head(5)

,id,estado,address,bicisDisponibles,anclajesDisponibles,lastUpdated,geometry.coordinates
0,279,IN_SERVICE,193- Pza. La Ermita,3,16,2026-07-22T11:53:09,"[-0.911215893796391, 41.63149540266168]"
1,278,IN_SERVICE,270- Delicias Autobuses,18,1,2026-07-22T11:53:09,"[-0.9107841716732368, 41.65951733457972]"
2,277,IN_SERVICE,150- Mrio. Siresa: Dr. Iranzo,2,16,2026-07-22T11:53:09,"[-0.8640994330671391, 41.64758556666017]"
3,276,IN_SERVICE,127- Navarra: Rioja,1,18,2026-07-22T11:53:09,"[-0.908685551690069, 41.655535911165344]"
4,275,IN_SERVICE,20- Camón Aznar: C. Augusto,19,0,2026-07-22T11:53:09,"[-0.8853921642559097, 41.65246416373115]"

El motivo de las columnas que eliminamos es que son datos que no nos sirven para analizar (fotos) y luego title y address es el mismo dato y ocua espacio innecesario.

Normalizamos nombres de columnas

In [10]:
mapeo = {
    "bicisDisponibles" :"bicis_disponibles",
    "anclajesDisponibles" : "anclajes_disponibles",
    "lastUpdated" : "last_updated"
}

df = df.rename(columns=mapeo)

### Fecha y Hora

In [11]:
df["last_updated"] = pd.to_datetime(df["last_updated"])

In [12]:
df["fecha"] = df["last_updated"].dt.date
df["mes"] = df["last_updated"].dt.month
df["dia"] = df["last_updated"].dt.day
df["dia_semana"] = df["last_updated"].dt.day_name(locale='es_ES')
df["hora"] = df["last_updated"].dt.hour
df["minutos"] = df["last_updated"].dt.minute

In [13]:
df.head(5)

,id,estado,address,bicis_disponibles,anclajes_disponibles,last_updated,geometry.coordinates,fecha,mes,dia,dia_semana,hora,minutos
0,279,IN_SERVICE,193- Pza. La Ermita,3,16,2026-07-22 11:53:09,"[-0.911215893796391, 41.63149540266168]",2026-07-22,7,22,Miércoles,11,53
1,278,IN_SERVICE,270- Delicias Autobuses,18,1,2026-07-22 11:53:09,"[-0.9107841716732368, 41.65951733457972]",2026-07-22,7,22,Miércoles,11,53
2,277,IN_SERVICE,150- Mrio. Siresa: Dr. Iranzo,2,16,2026-07-22 11:53:09,"[-0.8640994330671391, 41.64758556666017]",2026-07-22,7,22,Miércoles,11,53
3,276,IN_SERVICE,127- Navarra: Rioja,1,18,2026-07-22 11:53:09,"[-0.908685551690069, 41.655535911165344]",2026-07-22,7,22,Miércoles,11,53
4,275,IN_SERVICE,20- Camón Aznar: C. Augusto,19,0,2026-07-22 11:53:09,"[-0.8853921642559097, 41.65246416373115]",2026-07-22,7,22,Miércoles,11,53

### Longitud y Latitud

In [14]:
print(type(df["geometry.coordinates"].iloc[0]))

<class 'list'>

In [15]:
df['longitud'] = df['geometry.coordinates'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else x)
df['latitud'] = df['geometry.coordinates'].apply(lambda x: x[1] if isinstance(x, list) and len(x) > 0 else x)

In [16]:
df.head(5)

,id,estado,address,bicis_disponibles,anclajes_disponibles,last_updated,geometry.coordinates,fecha,mes,dia,dia_semana,hora,minutos,longitud,latitud
0,279,IN_SERVICE,193- Pza. La Ermita,3,16,2026-07-22 11:53:09,"[-0.911215893796391, 41.63149540266168]",2026-07-22,7,22,Miércoles,11,53,-0.911216,41.631495
1,278,IN_SERVICE,270- Delicias Autobuses,18,1,2026-07-22 11:53:09,"[-0.9107841716732368, 41.65951733457972]",2026-07-22,7,22,Miércoles,11,53,-0.910784,41.659517
2,277,IN_SERVICE,150- Mrio. Siresa: Dr. Iranzo,2,16,2026-07-22 11:53:09,"[-0.8640994330671391, 41.64758556666017]",2026-07-22,7,22,Miércoles,11,53,-0.864099,41.647586
3,276,IN_SERVICE,127- Navarra: Rioja,1,18,2026-07-22 11:53:09,"[-0.908685551690069, 41.655535911165344]",2026-07-22,7,22,Miércoles,11,53,-0.908686,41.655536
4,275,IN_SERVICE,20- Camón Aznar: C. Augusto,19,0,2026-07-22 11:53:09,"[-0.8853921642559097, 41.65246416373115]",2026-07-22,7,22,Miércoles,11,53,-0.885392,41.652464

Eliminamos la columna de geometry, ya que no hace mas falta.

In [17]:
df = df.drop(columns="geometry.coordinates")

In [18]:
df.head(5)

,id,estado,address,bicis_disponibles,anclajes_disponibles,last_updated,fecha,mes,dia,dia_semana,hora,minutos,longitud,latitud
0,279,IN_SERVICE,193- Pza. La Ermita,3,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.911216,41.631495
1,278,IN_SERVICE,270- Delicias Autobuses,18,1,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.910784,41.659517
2,277,IN_SERVICE,150- Mrio. Siresa: Dr. Iranzo,2,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.864099,41.647586
3,276,IN_SERVICE,127- Navarra: Rioja,1,18,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.908686,41.655536
4,275,IN_SERVICE,20- Camón Aznar: C. Augusto,19,0,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.885392,41.652464

### Separar número de estación

In [19]:
df["estacion"] = df["address"].str.split('-').str[0]

In [20]:
df.head(5)

,id,estado,address,bicis_disponibles,anclajes_disponibles,last_updated,fecha,mes,dia,dia_semana,hora,minutos,longitud,latitud,estacion
0,279,IN_SERVICE,193- Pza. La Ermita,3,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.911216,41.631495,193
1,278,IN_SERVICE,270- Delicias Autobuses,18,1,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.910784,41.659517,270
2,277,IN_SERVICE,150- Mrio. Siresa: Dr. Iranzo,2,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.864099,41.647586,150
3,276,IN_SERVICE,127- Navarra: Rioja,1,18,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.908686,41.655536,127
4,275,IN_SERVICE,20- Camón Aznar: C. Augusto,19,0,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.885392,41.652464,20

In [21]:
df["nombre_estacion"] = df["address"].str.split('-').str[1]

In [22]:
df.head(5)

,id,estado,address,bicis_disponibles,anclajes_disponibles,last_updated,fecha,mes,dia,dia_semana,hora,minutos,longitud,latitud,estacion,nombre_estacion
0,279,IN_SERVICE,193- Pza. La Ermita,3,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.911216,41.631495,193,Pza. La Ermita
1,278,IN_SERVICE,270- Delicias Autobuses,18,1,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.910784,41.659517,270,Delicias Autobuses
2,277,IN_SERVICE,150- Mrio. Siresa: Dr. Iranzo,2,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.864099,41.647586,150,Mrio. Siresa: Dr. Iranzo
3,276,IN_SERVICE,127- Navarra: Rioja,1,18,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.908686,41.655536,127,Navarra: Rioja
4,275,IN_SERVICE,20- Camón Aznar: C. Augusto,19,0,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.885392,41.652464,20,Camón Aznar: C. Augusto

Elimino la columna address ya que separe los datos en 2 columnas.

In [23]:
df = df.drop(columns="address")

In [24]:
df.head(5)

,id,estado,bicis_disponibles,anclajes_disponibles,last_updated,fecha,mes,dia,dia_semana,hora,minutos,longitud,latitud,estacion,nombre_estacion
0,279,IN_SERVICE,3,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.911216,41.631495,193,Pza. La Ermita
1,278,IN_SERVICE,18,1,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.910784,41.659517,270,Delicias Autobuses
2,277,IN_SERVICE,2,16,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.864099,41.647586,150,Mrio. Siresa: Dr. Iranzo
3,276,IN_SERVICE,1,18,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.908686,41.655536,127,Navarra: Rioja
4,275,IN_SERVICE,19,0,2026-07-22 11:53:09,2026-07-22,7,22,Miércoles,11,53,-0.885392,41.652464,20,Camón Aznar: C. Augusto

In [25]:
df.to_csv(PROCESSED_PATH / "datos_limpios.csv")

In [26]:
from src.cargar_sqlite import cargar_a_sqlite

cargar_a_sqlite(PROCESSED_PATH / "datos_limpios.csv")